services:
#    lottery.example:
#        class: LotteryBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
#

    lottery.design.meet:
        class:  LotteryBundle\Service\Meet
        arguments: ["@service_container"]
