<?php

namespace LotteryBundle\Repository;

/**
 * BlackListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlackListRepository extends \Doctrine\ORM\EntityRepository
{
}
