<?php

namespace LotteryBundle\Repository;

/**
 * MeetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetRepository extends \Doctrine\ORM\EntityRepository
{
}
