<?php

namespace LotteryBundle\Repository;

/**
 * RedListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedListRepository extends \Doctrine\ORM\EntityRepository
{
}
